#!/bin/bash
docker exec -t nopasaran-db-1 pg_dump -U $(grep POSTGRES_USER .env | cut -d '=' -f2) -d $(grep POSTGRES_DB .env | cut -d '=' -f2) > ../backups/backup_$(date +%Y-%m-%d_%H-%M-%S).sql
tar -czvf ../backups/media_backup_$(date +%Y-%m-%d_%H-%M-%S).tar.gz -C /home/gregb/nopasaran/infra/data uploads

